### PR TITLE
Standardize API naming：

### PR DESCRIPTION
**Pull request by Smao0875**
1. touched swagger file.
2. touched unit test file.
3. soft delete is implemented.

Tested:
works well and all unit tests passed.

### CODE REVIEW

**Comment by liptonday** [comment]
@Smao0875 merge conflicts 😜

**Comment by Smao0875** [comment]
Is there anything I can do?

**Comment by Smao0875** [comment]
I think I just resolved the conflict.

**Review by liptonday — APPROVED** [review]
👍

**Pull request merged**
